# Generated by Django 4.2 on 2023-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="google_sheet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
