!function(){var a,o,s,n,l,r,e,t,c,d
if(AOS.init({duration:800,easing:"slide"}),(c=jQuery)(window).stellar({responsive:!0,parallaxBackgrounds:!0,parallaxElements:!0,horizontalScrolling:!1,hideDistantElements:!1,scrollProperty:"scroll"}),c(".js-fullheight").css("height",c(window).height()),c(window).resize(function(){c(".js-fullheight").css("height",c(window).height())}),setTimeout(function(){0<c("#ftco-loader").length&&c("#ftco-loader").removeClass("show")},1),c.Scrollax(),c(".carousel-testimony").owlCarousel({center:!0,loop:!0,items:1,margin:30,stagePadding:0,nav:!0,navText:['<span class="ion-ios-arrow-back">','<span class="ion-ios-arrow-forward">'],responsive:{0:{items:1},600:{items:2},1e3:{items:3}}}),c("nav .dropdown").hover(function(){var e=c(this)
e.addClass("show"),e.find("> a").attr("aria-expanded",!0),e.find(".dropdown-menu").addClass("show")},function(){var e=c(this)
e.removeClass("show"),e.find("> a").attr("aria-expanded",!1),e.find(".dropdown-menu").removeClass("show")}),c("#dropdown04").on("show.bs.dropdown",function(){console.log("show")}),c(window).scroll(function(){var e=c(this).scrollTop(),t=c(".ftco_navbar"),a=c(".js-scroll-wrap")
150<e&&(t.hasClass("scrolled")||t.addClass("scrolled")),e<150&&t.hasClass("scrolled")&&t.removeClass("scrolled sleep"),350<e&&(t.hasClass("awake")||t.addClass("awake"),0<a.length)&&a.addClass("sleep"),e<350&&(t.hasClass("awake")&&(t.removeClass("awake"),t.addClass("sleep")),0<a.length)&&a.removeClass("sleep")}),c("#section-counter").waypoint(function(e){var a
"down"!==e||c(this.element).hasClass("ftco-animated")||(a=c.animateNumber.numberStepFactories.separator(","),c(".number").each(function(){var e=c(this),t=e.data("number")
console.log(t),e.animateNumber({number:t,numberStep:a},7e3)}))},{offset:"95%"}),c(".ftco-animate").waypoint(function(e){"down"!==e||c(this.element).hasClass("ftco-animated")||(c(this.element).addClass("item-animate"),setTimeout(function(){c("body .ftco-animate.item-animate").each(function(e){var t=c(this)
setTimeout(function(){var e=t.data("animate-effect")
"fadeIn"===e?t.addClass("fadeIn ftco-animated"):"fadeInLeft"===e?t.addClass("fadeInLeft ftco-animated"):"fadeInRight"===e?t.addClass("fadeInRight ftco-animated"):t.addClass("fadeInUp ftco-animated"),t.removeClass("item-animate")},50*e,"easeInOutExpo")})},100))},{offset:"95%"}),c(".smoothscroll[href^='#'], #ftco-nav ul li a[href^='#']").on("click",function(e){e.preventDefault()
var t=this.hash,e=c(".navbar-toggler")
c("html, body").animate({scrollTop:c(t).offset().top},700,"easeInOutExpo",function(){window.location.hash=t}),e.is(":visible")&&e.click()}),c("body").on("activate.bs.scrollspy",function(){console.log("nice")}),c(".image-popup").magnificPopup({type:"image",closeOnContentClick:!0,closeBtnInside:!1,fixedContentPos:!0,mainClass:"mfp-no-margins mfp-with-zoom",gallery:{enabled:!0,navigateByImgClick:!0,preload:[0,1]},image:{verticalFit:!0},zoom:{enabled:!0,duration:300}}),c(".popup-youtube, .popup-vimeo, .popup-gmaps").magnificPopup({disableOn:700,type:"iframe",mainClass:"mfp-fade",removalDelay:160,preloader:!1,fixedContentPos:!1}),$(".next").click(function(){if(e)return!1
e=!0,a=$(this).parent(),o=$(this).parent().next(),$("#progressbar li").eq($("fieldset").index(o)).addClass("active"),o.show(),a.animate({opacity:0},{step:function(e,t){r=1-.2*(1-e),n=50*e+"%",l=1-e,a.css({transform:"scale("+r+")",position:"absolute"}),o.css({left:n,opacity:l})},duration:800,complete:function(){a.hide(),e=!1},easing:"easeInOutBack"})}),$(".previous").click(function(){if(e)return!1
e=!0,a=$(this).parent(),s=$(this).parent().prev(),$("#progressbar li").eq($("fieldset").index(a)).removeClass("active"),s.show(),a.animate({opacity:0},{step:function(e,t){r=.8+.2*(1-e),n=50*(1-e)+"%",l=1-e,a.css({left:n}),s.css({transform:"scale("+r+")",opacity:l})},duration:800,complete:function(){a.hide(),e=!1},easing:"easeInOutBack"})}),$(".submit").click(function(){return!1}),null!=(t=document.getElementById("update-item"))&&t.length<1)for(i=0;i<t.length;i++)t[i].addEventListener("click",function(){var e,t,a=this.dataset.product,o=this.dataset.action
console.log("productId:",a,"Action:",o),console.log("USER:",user),"AnonymousUser"==user?(t=a,e=o,console.log("User is not authenticated"),"add"==e&&(null==cart[t]?cart[t]={quantity:1}:cart[t].quantity+=1),"remove"==e&&(--cart[t].quantity,cart[t].quantity<=0)&&(console.log("Item should be deleted"),delete cart[t]),console.log("CART:",cart),document.cookie="cart="+JSON.stringify(cart)+";domain=;path=/",location.reload()):(e=a,t=o,console.log("User is authenticated, sending data..."),fetch("/update_item/",{method:"POST",headers:{"Content-Type":"application/json","X-CSRFToken":csrftoken},body:JSON.stringify({productId:e,action:t})}).then(e=>e.json()).then(e=>{location.reload()}))});(d=jQuery)(".toggle-password").click(function(){d(this).toggleClass("zmdi-eye zmdi-eye-off")
var e=d(d(this).attr("toggle"))
"password"==e.attr("type")?e.attr("type","text"):e.attr("type","password")})
var u=document.querySelector(".hamburger")
const m=document.querySelector(".nav-links"),f=document.querySelectorAll(".nav-links li")
u.addEventListener("click",()=>{m.classList.toggle("open"),f.forEach(e=>{e.classList.toggle("fade")})})}.call(this)
