# Generated by Django 4.2 on 2023-04-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_homepage_aboutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="content_2",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="title_2",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content_2",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_2",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
