# Generated by Django 4.2 on 2023-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_aboutpage_content_2_aboutpage_title_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="content_2_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="content_2_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="content_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="title_2_ar",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="title_2_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="title_ar",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="title_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content_2_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content_2_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_2_ar",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_2_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_ar",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_en",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
