# Generated by Django 4.1.5 on 2023-01-31 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(null=True, upload_to="profile_pics")),
                ("bio", models.TextField(blank=True, max_length=300)),
                (
                    "committee",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT", "IT"),
                            ("Design", "Design"),
                            ("PR", "PR"),
                            ("Logistics", "Logistics"),
                            ("HR", "HR"),
                            ("Marketing", "Marketing"),
                            ("Coaching", "Coaching"),
                            ("Media", "Media"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Member", "Member"),
                            ("Head", "Head"),
                            ("Vice", "Vice"),
                            ("Operations", "Operations"),
                            ("President", "President"),
                        ],
                        default="Member",
                        max_length=20,
                    ),
                ),
                ("awards", models.TextField(blank=True, max_length=300)),
                ("experience", models.TextField(blank=True, max_length=300)),
                ("achievement", models.TextField(blank=True, max_length=300)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
