# Generated by Django 3.0.6 on 2020-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
