# Generated by Django 4.1.7 on 2023-03-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_committee_remove_profile_committee_profile_committee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="committee",
        ),
        migrations.AddField(
            model_name="profile",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.committee",
            ),
        ),
    ]
