# Generated by Django 3.0.6 on 2020-06-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
