# Generated by Django 3.0.6 on 2020-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='committee',
            field=models.CharField(choices=[('IT', 'IT'), ('Design', 'Design'), ('ER', 'ER'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Coaching', 'Coaching'), ('Media', 'Media'), ('Branding', 'Branding')], default='IT', max_length=10),
        ),
    ]
