# Generated by Django 4.1.7 on 2023-03-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_profile_committee_profile_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="description",
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
