# Generated by Django 4.1.7 on 2023-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_committee_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="behance",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
