# Generated by Django 3.0.6 on 2020-06-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200604_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
