# Generated by Django 4.1.7 on 2023-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_profile_behance_profile_facebook_profile_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dribbble",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
