# Generated by Django 3.0.6 on 2020-06-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200604_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(default='', max_length=300),
        ),
    ]
