# Generated by Django 4.1.7 on 2023-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_profile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="youtube",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
