# Generated by Django 4.1.7 on 2023-03-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hide_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="hide_phone",
            field=models.BooleanField(default=False),
        ),
    ]
