# Generated by Django 4.1.7 on 2023-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_profile_hide_email_profile_hide_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="hide_email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="hide_phone",
        ),
        migrations.AddField(
            model_name="profile",
            name="show_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_phone",
            field=models.BooleanField(default=True),
        ),
    ]
