# Generated by Django 4.1.7 on 2023-03-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_profile_hide_email_remove_profile_hide_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="flickr",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
