# Generated by Django 4.1.7 on 2023-04-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_profile_flickr"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pydenticon",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
