# Generated by Django 4.1.7 on 2023-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_profile_pydenticon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pydenticon",
            field=models.ImageField(null=True, upload_to="profile_pics"),
        ),
    ]
