# Generated by Django 3.0.6 on 2020-06-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200604_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interests',
            new_name='awards',
        ),
    ]
