# Generated by Django 3.0.6 on 2020-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200605_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='achievement',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
