# Generated by Django 3.0.6 on 2020-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200607_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='awards',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
