# Generated by Django 3.1.3 on 2020-11-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200607_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='committee',
            field=models.CharField(choices=[('IT', 'IT'), ('Design', 'Design'), ('ER', 'ER'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Coaching', 'Coaching'), ('Media', 'Media'), ('Branding', 'Branding')], default='', max_length=10),
        ),
    ]
