# Generated by Django 4.1.3 on 2022-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
