# Generated by Django 4.1.3 on 2022-12-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_id_alter_registrationcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='committee',
            field=models.CharField(choices=[('IT', 'IT'), ('Design', 'Design'), ('PR', 'PR'), ('Logistics', 'Logistics'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Coaching', 'Coaching'), ('Media', 'Media')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Member', 'Member'), ('Head', 'Head'), ('Vice', 'Vice'), ('Operations', 'Operations'), ('President', 'President')], default='Member', max_length=20),
        ),
    ]
