# Generated by Django 4.1.3 on 2023-01-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_profile_image'),
        ('users', '0030_alter_profile_committee'),
    ]

    operations = [
    ]
