# Generated by Django 4.1.3 on 2023-01-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_merge_20230114_1945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.png", upload_to="profile_pics"),
        ),
    ]
