# Generated by Django 4.1.3 on 2023-01-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="achievement",
            field=models.TextField(blank=True, default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="awards",
            field=models.TextField(blank=True, default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="profile",
            name="experience",
            field=models.TextField(blank=True, default="", max_length=300),
            preserve_default=False,
        ),
    ]
