# Generated by Django 4.1.5 on 2023-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_alter_profile_achievement_alter_profile_awards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(null=True, upload_to="profile_pics"),
        ),
    ]
