[tool.poetry]
name = "tedx"
version = "0.1.0"
description = ""
authors = ["Mazen Omar <wildlifemain1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.3"
pillow = "^9.3.0"
django-crispy-forms = "^1.14.0"
pandas = "^1.5.1"
django-maintenance-mode = "^0.16.3"
django-ckeditor = "^6.5.1"
python-decouple = "^3.6"
python-gettext = "^4.1"
six = "^1.16.0"
qrcode = "^7.3.1"
selenium = "^4.7.2"
xhtml2pdf = "^0.2.8"
django-colorfield = "^0.8.0"
pylint-django = "^2.5.3"
pylint = "^2.15.10"
webdriver-manager = "^3.8.5"
coverage = "^7.0.5"
django-debug-toolbar = "^3.8.1"
dill = "^0.3.6"
django-pwa = "^1.1.0"
extcolors = "^1.0.0"
matplotlib = "^3.6.3"
django-htmlmin = "^0.11.0"
django-pipeline = "^2.0.9"
uvicorn = "^0.20.0"
gunicorn = "^20.1.0"
whitenoise = "^6.3.0"


[tool.poetry.group.dev.dependencies]
black = {version = "^23.1a1", allow-prereleases = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
