# Generated by Django 3.2.1 on 2021-05-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_recieved',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='ticket_recieved',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
