# Generated by Django 4.1.3 on 2022-12-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_ticket_recieved_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='ticket',
        ),
    ]
