# Generated by Django 4.1.3 on 2022-12-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_qrcode_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='ticket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.ticketform'),
        ),
    ]
