# Generated by Django 4.1.3 on 2023-01-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_qrcode_id_alter_ticket_recieved_id_and_more'),
        ('payment', '0005_qrcode_ticket'),
    ]

    operations = [
    ]
