# Generated by Django 4.1.5 on 2023-01-31 13:44

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#ff2a2a", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "font_color",
                    colorfield.fields.ColorField(
                        default="#ffffff", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, null=True)),
                ("image", models.ImageField(blank=True, upload_to="reports")),
                ("remarks", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
