# Generated by Django 4.1.5 on 2023-01-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="palette",
            field=models.ImageField(blank=True, upload_to="palette"),
        ),
    ]
