# Generated by Django 4.1.5 on 2023-02-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_design_palette"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="palette",
            field=models.ImageField(null=True, upload_to="palette"),
        ),
    ]
