# Generated by Django 4.1.7 on 2023-04-02 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_design_palette"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Design",
        ),
    ]
