# Generated by Django 4.1.3 on 2022-12-25 19:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='color',
            field=colorfield.fields.ColorField(default='#ff2a2a', image_field=None, max_length=18, samples=None),
        ),
    ]
