# Generated by Django 4.1.3 on 2022-12-25 20:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_design_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='font_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
    ]
