# Generated by Django 3.2.7 on 2021-09-05 11:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AlterField(
            model_name='contact',
            name='reply',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
