# Generated by Django 4.1.7 on 2023-03-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_videos_membername_videos_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
