# Generated by Django 3.2.7 on 2021-09-05 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210905_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='date_subscribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
