# Generated by Django 4.1.3 on 2022-12-23 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_subscribe_date_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('talk_name', models.CharField(max_length=12)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
