# Generated by Django 4.1.5 on 2023-03-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_videos_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speakers",
            name="image",
        ),
        migrations.AlterField(
            model_name="speakers",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="ImageSpeakers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="speaker_pics"),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.speakers"
                    ),
                ),
            ],
        ),
    ]
