# Generated by Django 4.1.5 on 2023-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_speakers_image_alter_speakers_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakers",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
