# Generated by Django 4.1.3 on 2022-12-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='speakers_pics'),
        ),
    ]
