# Generated by Django 4.1.5 on 2023-03-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_speakers_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakers",
            name="facebook",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="speakers",
            name="instagram",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="speakers",
            name="twitter",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="speakers",
            name="website",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="speakers",
            name="youtube",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
