# Generated by Django 4.1.3 on 2022-12-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_speakers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='talk_name',
            field=models.CharField(max_length=20),
        ),
    ]
