# Generated by Django 4.1.3 on 2022-12-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_speakers_talk_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakers',
            old_name='created',
            new_name='date_posted',
        ),
    ]
