# Generated by Django 4.1.3 on 2022-12-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_created_speakers_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
