# Generated by Django 4.1.3 on 2022-12-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_attendee'),
        ('base', '0008_alter_speakers_name'),
    ]

    operations = [
    ]
