# Generated by Django 3.2.1 on 2021-05-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes')),
            ],
        ),
        migrations.CreateModel(
            name='TicketForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Recieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('qr_code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.qrcode')),
            ],
        ),
        migrations.AddField(
            model_name='qrcode',
            name='ticket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.ticketform'),
        ),
    ]
