# Generated by Django 4.1.5 on 2023-01-31 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_merge_20230114_1945"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TicketForm",
            new_name="Ticket",
        ),
        migrations.RenameModel(
            old_name="Ticket_Recieved",
            new_name="TicketRecieved",
        ),
    ]
