name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
  pull_requests:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
        uses: actions/add-to-project@v0.4.0
        with:
          # You can target a repository in a different organization
          # to the iss
          project-url: https://github.com/users/MezoPeeta/projects/10/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug, needs-triage
          label-operator: OR