name: Pylint

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          echo "pylint-error"=$(pylint --load-plugins pylint_django --django-settings-module=TEDx.settings  --ignore=migrations $(git ls-files '*.py')) >> $GITHUB_OUTPUT
        id: P0
      - name: Comment current pull request
        uses: alawiii521/current-pr-comment@v1.0
        with:
          comment: ${{ env.GITHUB_OUTPUT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
