# Generated by Django 3.1.3 on 2020-11-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcuts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='product_default.jpeg', upload_to='products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
