# Generated by Django 3.1.3 on 2020-11-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201124_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcuts',
            name='Image',
            field=models.ImageField(default='product_default.jpg', upload_to='products'),
        ),
    ]
