# Generated by Django 4.1.7 on 2023-04-11 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_coupon_customer_imageproducts_order_orderitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="description",
        ),
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True, default="product_default.jpg", upload_to="products"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
