# Generated by Django 3.1.3 on 2020-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
