# Generated by Django 4.1.5 on 2023-01-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="name",
            field=models.CharField(default="Product Name", max_length=200),
        ),
    ]
