# Generated by Django 4.1.7 on 2023-03-23 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_products_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"ordering": ["-created_at"]},
        ),
    ]
